wandb_version: 1

script_dir:
  desc: null
  value: /Users/nadavoutmezguine/Library/CloudStorage/Dropbox/Lerning/PAdam/python
data_dir:
  desc: null
  value: ./data/CIFAR10
out_dir:
  desc: null
  value: ./CIFAR_results
save_checkpoints:
  desc: null
  value: true
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: PAdam
wandb_run_name:
  desc: null
  value: ResNet181701733643.753611
num_workers:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 400
epochs:
  desc: null
  value: 1
optimizer_name:
  desc: null
  value: AdamW
max_lr:
  desc: null
  value: 0.001
lambda_p:
  desc: null
  value: 0.001
p_norm:
  desc: null
  value: 0.8
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 1000
lr_decay_frac:
  desc: null
  value: 0.8
lr_decay_epochs:
  desc: null
  value: 80
min_lr:
  desc: null
  value: 1.0e-05
small_weights_threshold:
  desc: null
  value: 1.0e-13
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: mps
dtype:
  desc: null
  value: float16
compile:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701733733.205392
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.17
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
